### ISSUE TITLE
Updater breaks after update to windows 2004

### ISSUE THREAD

**Issue by cujomalainey** [SirMangler/PrimeHack-Updater#11]
Version 2004
OS Build 19041.388

This is from the event log.
```
Faulting application name: PrimeHack.Updater.exe, version: 1.0.5.0, time stamp: 0x5eaf858f
Faulting module name: KERNELBASE.dll, version: 10.0.19041.388, time stamp: 0xa2224bb6
Exception code: 0xe0434352
Fault offset: 0x00129862
Faulting process id: 0x5848
Faulting application start time: 0x01d65f064d3c905b
Faulting application path: C:\Users\Curtis\Downloads\PrimeHack.Updater.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 650ac0e5-8778-4337-b687-aec9dbcacfc3
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by SirMangler** [comment]
The event log doesn't give very useful information to an application developer such as myself. Did the Updater itself present any errors? Perhaps something in the console? 

I do not have the 2004 update, honestly I wouldn't be surprised if this is just a problem with Windows, the error did occur from `KERNELBASE.dll` after-all. 

I will have to update my machine to test this or we wait until a further update to see if the error persists. One thing you may attempt is deleting `Updater.cfg` and running the updater as administrator.

**Comment by cujomalainey** [comment]
It did but I was unable to relaunch the application to see if it was a one off. I will try deleting the config tonight and see what I get.

**Comment by cujomalainey** [comment]
no idea what the issue was, but installed some more updates and the tool fixed itself

**Comment by SirMangler** [comment]
Must be a problem with Windows. Glad it's resolved.
