### ISSUE TITLE
Add RVZ format to the list of supported formats for autolaunch

### ISSUE THREAD

**Issue by shinrax2** [SirMangler/PrimeHack-Updater#14]
as the title says please add the RVZ format to the list of accepted formats for the autolaunch feature for primehack updater

current primehack(v1.0.2a) supports it

**Comment by SirMangler** [comment]
This already exists but isn't in the latest release. The updater is due a refactor (rewriting parts of the code) but I have been busy with PrimeHack proper.

https://github.com/SirMangler/PrimeHack-Updater/commit/9439b512ed1339f5acc9063a479bbcc02c5de3a4

**Comment by shinrax2** [comment]
cool then ill happily await the new release :D

and thanks for the programm its pretty cool :D
