### ISSUE TITLE
Trilogy will not load

### ISSUE THREAD

**Issue by timmytoofye** [SirMangler/PrimeHack-Updater#16]
Hey, im not sure what really happened to my game but I played metroid prime 3 and got to about 30% done with the game and now the trilogy just wont load up anymore. I click play trilogy and I just get a white screen. Then when I close it, it gives me the error message that Dolphin.exe isnt responding. I downloaded the same version of prime hack again and booted up the game just fine but now my save file is in the other download. Is there any way I could move the save file from the old prime hack onto the new one? I wasnt sure if I should message you or Shiiion, so sorry in advance.

**Comment by SirMangler** [comment]
https://github.com/SirMangler/PrimeHack-Updater/issues/8
