### ISSUE TITLE
no longer working after using a wiimote on dolphin normally 

### ISSUE THREAD

**Issue by lucian1311** [SirMangler/PrimeHack-Updater#17]
after i used a wiimote on dolphin normally (without launchin primehack) when i attempt to play metroid prime trilogy it just says : communications with the wii remote have been interrupted. i have no idea how to fix this (it was working perfectly before i used a wiimote)

**Comment by SirMangler** [comment]
https://github.com/SirMangler/PrimeHack-Updater/issues/8
