### ISSUE TITLE
Keybinds not working for visors or beams

### ISSUE THREAD

**Issue by romanbair** [SirMangler/PrimeHack-Updater#3]
After updating, the keybinds aren't working for only the beams and visors. Is there a way I can change the settings to where I can pull the beam/visor interface up and move the cursor to w/e I need until this is resolved?

**Comment by SirMangler** [comment]
There aren't any known issues with the beam/visor selection. We currently do not have a way to disable the hack's method of selecting beams and visors. 

You can view or try change your binds here:
https://github.com/shiiion/Dolphin/wiki/Installation#primehack--fps-settings

If this does not resolve your problem, please feel free to join the PrimeHack discord server.
https://discord.gg/tchQne2
