### ISSUE TITLE
Switches to the wrongbeam depending on order of input

### ISSUE THREAD

**Issue by LogiGameStar** [SirMangler/PrimeHack-Updater#4]
Example: If you are on Beam 1 and you switch by inputting "Beam 3" then input "Previous Beam", you switch back to beam 1 when you should have gone to beam 2. 

There are more wrong beam switches occurring just like this from pressing a key that switches to a specific beam followed with pressing a misc key for previous or next beam.

**Comment by SirMangler** [comment]
1. This isn't the correct [PrimeHack repository](https://github.com/shiiion/dolphin). This is the updater, this codebase is totally unrelated.

2. Thank you for reporting this. The issue with hitting "Beam 3", followed by "Previous Beam" resulting in the wrong beam order has been identified and we shall look into resolving it. If there is more to this problem, please either create an issue on the correct repository or write to us in our [Discord server](https://discord.gg/tchQne2).
