### ISSUE TITLE
Controls revert back to normal during Defense Drone fight (MP3)

### ISSUE THREAD

**Issue by Oppion44** [SirMangler/PrimeHack-Updater#5]
When I approach the Boost Ball in MP3 in Sky Town and the battle against the Defense Drone starts the mouse/crosshair isn't locked to the center anymore, instead it behaves like the normal Wiimote crosshair. I can't change visors by pressing my assigned keys as well.

Video: https://www.youtube.com/watch?v=IFq9fRwhq_k

**Comment by SirMangler** [comment]
https://github.com/shiiion/Ishiiruka/commit/c194b293c4e96fc13b8abc09ec78f0b9195fcd1f

*Please note this repository is for the **Updater***.

A change has already been made to resolve this bug. Thank you for reporting this. As you can see on the readme page, the official repository is:
https://github.com/shiiion/dolphin/

Our secondary repository for the Ishiiruka version is here:
https://github.com/shiiion/Ishiiruka/

I recommend you join our Discord. Again thanks for reporting.

**Comment by Oppion44** [comment]
Thanks for confirming this. I posted this here because I couldn't see an "Issues" tab on either of those other repositories and thought the best chance someone will see my report will be here. Any news on when the new update will come out?

What's your Discord? The one I joined before making my report here (https://discord.gg/tchQne2) is simply dead with just a welcome page.

**Comment by Oppion44** [comment]
> 
> 
> [shiiion/Ishiiruka@c194b29](https://github.com/shiiion/Ishiiruka/commit/c194b293c4e96fc13b8abc09ec78f0b9195fcd1f)
> 
> _Please note this repository is for the **Updater**_.
> 
> A change has already been made to resolve this bug. Thank you for reporting this. As you can see on the readme page, the official repository is:
> https://github.com/shiiion/dolphin/
> 
> Our secondary repository for the Ishiiruka version is here:
> https://github.com/shiiion/Ishiiruka/
> 
> I recommend you join our Discord. Again thanks for reporting.

Thanks for confirming this. I posted this here because I couldn't see an "Issues" tab on either of those other repositories and thought the best chance someone will see my report will be here. Any news on when the new update will come out? I'm thinking about waiting or continuing with my Wiimote on the real Dolphin atm.

What's your Discord? The one I joined before making my report here (https://discord.gg/tchQne2) is simply dead with just a welcome page.

**Comment by SirMangler** [comment]
> What's your Discord? The one I joined before making my report here (https://discord.gg/tchQne2) is simply dead with just a welcome page.

You should have received a DM from a bot explaining what to do, did this not happen? Please see the rules section of the welcome page, it explains what to do.

**Comment by Oppion44** [comment]
> 
> 
> > What's your Discord? The one I joined before making my report here (https://discord.gg/tchQne2) is simply dead with just a welcome page.
> 
> You should have received a DM from a bot explaining what to do, did this not happen? Please see the rules section of the welcome page, it explains what to do.

Alright, I have found what to do, thanks. I will continue with my Wiimote to pass the boss.
