### ISSUE TITLE
Visual Issues

### ISSUE THREAD

**Issue by BruhCringe** [SirMangler/PrimeHack-Updater#7]
When trying to play Metroid Prime on the trilogy, during the opening cutscene my screen starts flashing pink and the "Metroid Prime Loading" screen is stuck on the top left corner of my screen. Does anyone know what this is?

**Comment by SirMangler** [comment]
This repository is for the *Updater*. Not [PrimeHack](https://github.com/shiiion/dolphin) itself.

Please refer to the wiki on resolving visual glitches:
https://github.com/shiiion/dolphin/wiki/Glitches-and-Bugs#visual-glitches
