### ISSUE TITLE
Game stutters then crashes

### ISSUE THREAD

**Issue by Domtron77** [SirMangler/PrimeHack-Updater#9]
I’ve been trying to get primehack to work but whenever I’m playing for a few minutes the screen stutters between the game and the loading screen for a bit before crashing and closing the game. At first I thought I downloaded a bad iso so I downloaded another iso but it’s the same problem, I’ve played MPT through the updater and regular primehack but they both have the same problem.

**Comment by SirMangler** [comment]
https://github.com/SirMangler/PrimeHack-Updater/issues/8
